<a href="https://colab.research.google.com/github/lalasray/Render-3D-pose-from-a-video/blob/main/Notebook/Facebook_VideoPose3D_Inference_in_the_wild_Detectron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Install pytorch & Caffe 
!wget https://anaconda.org/pytorch/pytorch/1.2.0/download/linux-64/pytorch-1.2.0-py3.6_cuda10.0.130_cudnn7.6.2_0.tar.bz2
!tar xvjf pytorch-1.2.0-py3.6_cuda10.0.130_cudnn7.6.2_0.tar.bz2
!cp -r lib/python3.6/site-packages/* /usr/local/lib/python3.6/dist-packages/

--2021-12-25 12:33:53--  https://anaconda.org/pytorch/pytorch/1.2.0/download/linux-64/pytorch-1.2.0-py3.6_cuda10.0.130_cudnn7.6.2_0.tar.bz2
Resolving anaconda.org (anaconda.org)... 104.17.92.24, 104.17.93.24, 2606:4700::6811:5c18, ...
Connecting to anaconda.org (anaconda.org)|104.17.92.24|:443... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: https://binstar-cio-packages-prod.s3.amazonaws.com/5a11922b393ec61208ae9668/5d4c44f5fe6b2a65c4c559c7?response-content-disposition=attachment%3B%20filename%3D%22pytorch-1.2.0-py3.6_cuda10.0.130_cudnn7.6.2_0.tar.bz2%22%3B%20filename%2A%3DUTF-8%27%27pytorch-1.2.0-py3.6_cuda10.0.130_cudnn7.6.2_0.tar.bz2&response-content-type=application%2Fx-tar&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=60&X-Amz-Date=20211225T123354Z&X-Amz-SignedHeaders=host&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEHgaCXVzLWVhc3QtMSJIMEYCIQD9gTQJ6Uv1lZeiSkIOCbxQUbqe0Ug4GMh7B5fPiPY%2B2wIhAPnD%2FnmaWiEdBHpdJp%2BGQNUffj6x%2BzwqpsPYUdN2FS8tKvoDCHEQABoMNDU1ODY0MDk4

In [2]:
#Install coco dataset
!apt-get install python-dev
!pip install cython
!pip install pycocotools
!git clone https://github.com/cocodataset/cocoapi.git
!cd cocoapi/PythonAPI && make install

import os
os.environ['COCOAPI'] = ":/content/cocoapi"

Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-dev is already the newest version (2.7.15~rc1-1).
0 upgraded, 0 newly installed, 0 to remove and 37 not upgraded.
Cloning into 'cocoapi'...
remote: Enumerating objects: 975, done.
remote: Total 975 (delta 0), reused 0 (delta 0), pack-reused 975
Receiving objects: 100% (975/975), 11.72 MiB | 24.06 MiB/s, done.
Resolving deltas: 100% (576/576), done.
# install pycocotools to the Python site-packages
python setup.py build_ext install
running build_ext
cythoning pycocotools/_mask.pyx to pycocotools/_mask.c
/usr/local/lib/python3.7/dist-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /content/cocoapi/PythonAPI/pycocotools/_mask.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
building 'pycocotools._mask' extension
creating build
creating build/common
creating build/temp.

In [3]:
#Install facebook detectron
!git clone https://github.com/facebookresearch/detectron
!pip install -r detectron/requirements.txt
!cd detectron && make
!python detectron/detectron/tests/test_spatial_narrow_as_op.py

Cloning into 'detectron'...
remote: Enumerating objects: 1377, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 1377 (delta 1), reused 2 (delta 0), pack-reused 1370
Receiving objects: 100% (1377/1377), 4.38 MiB | 15.92 MiB/s, done.
Resolving deltas: 100% (825/825), done.
     |████████████████████████████████| 375 kB 5.4 MB/s 
  Created wheel for pyyaml: filename=PyYAML-3.12-cp37-cp37m-linux_x86_64.whl size=43073 sha256=e1bca92fdee573bec73ea62e4d1b177d62a9bf9ee96eb8ff6f9bbd8c3a8476b7
  Stored in directory: /root/.cache/pip/wheels/21/cc/0a/8f691c938b079b07fa17a2e2940e3faae0a3dfb3ff5b3ac356
Successfully built pyyaml
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
python setup.py develop --user
Compiling detectron/utils/cython_bbox.pyx because it changed.
Compiling detectron/utils/cython_nms.pyx because it changed.
[1/2] Cythoni

In [4]:
#copy file from VideoPose3d
!git clone https://github.com/facebookresearch/VideoPose3D
!cp VideoPose3D/inference/infer_video.py detectron/tools/infer_video.py

Cloning into 'VideoPose3D'...
remote: Enumerating objects: 121, done.
remote: Total 121 (delta 0), reused 0 (delta 0), pack-reused 121
Receiving objects: 100% (121/121), 9.53 MiB | 26.30 MiB/s, done.
Resolving deltas: 100% (41/41), done.


In [12]:
#copy file from helper_video2bvh
!git clone https://github.com/lalasray/helper_video2bvh
!mv "/content/helper_video2bvh/bvh_skeleton" "/content"
!mv "/content/helper_video2bvh/utils" "/content"
!mv "/content/helper_video2bvh/cameras.h5" "/content"

fatal: destination path 'helper_video2bvh' already exists and is not an empty directory.
mv: cannot stat '/content/helper_video2bvh/bvh_skeleton': No such file or directory
mv: cannot stat '/content/helper_video2bvh/utils': No such file or directory
mv: cannot stat '/content/helper_video2bvh/cameras.h5': No such file or directory
rm: cannot remove '/content/helper_video2bvh': Is a directory


In [6]:
#Download Pretrained Human3.6m Coco Model
!mkdir VideoPose3D/checkpoint
os.chdir('VideoPose3D/checkpoint')
!wget https://dl.fbaipublicfiles.com/video-pose-3d/pretrained_h36m_detectron_coco.bin
os.chdir('../..')

--2021-12-25 12:09:47--  https://dl.fbaipublicfiles.com/video-pose-3d/pretrained_h36m_detectron_coco.bin
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 104.22.75.142, 104.22.74.142, 172.67.9.4, ...
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|104.22.75.142|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 67892577 (65M) [application/octet-stream]
Saving to: ‘pretrained_h36m_detectron_coco.bin’

pretrained_h36m_det 100%[===================>]  64.75M  10.5MB/s    in 7.3s    

2021-12-25 12:09:56 (8.81 MB/s) - ‘pretrained_h36m_detectron_coco.bin’ saved [67892577/67892577]



In [7]:
#Download Youtube Video for 3D Pose Estimation
YOUTUBE_ID ='z6PJMT2y8GQ'


!pip install -q youtube-dl
#download video
!youtube-dl -f 'bestvideo[ext=mp4]' --output "youtube.%(ext)s" https://www.youtube.com/watch?v=$YOUTUBE_ID

!mkdir videos   
  
# cut the first 9 seconds
!ffmpeg -y -loglevel info -i youtube.mp4 -ss 00:00:03 -t 00:00:08 videos/video.mp4

#!ffmpeg -i videos/video.mp4 -filter "minterpolate='fps=50'" -crf 0 videos/video50fps.mp4

     |████████████████████████████████| 1.9 MB 4.3 MB/s 
[youtube] z6PJMT2y8GQ: Downloading webpage
[download] Destination: youtube.mp4
[download] 100% of 4.22MiB in 01:42
ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --

In [8]:
#Compute 2D Coordinates with Detectron
!mkdir output
!python detectron/tools/infer_video.py \
    --cfg detectron/configs/12_2017_baselines/e2e_keypoint_rcnn_R-101-FPN_s1x.yaml \
    --output-dir output \
    --image-ext mp4 \
    --wts https://dl.fbaipublicfiles.com/detectron/37698009/12_2017_baselines/e2e_keypoint_rcnn_R-101-FPN_s1x.yaml.08_45_57.YkrJgP6O/output/train/keypoints_coco_2014_train:keypoints_coco_2014_valminusminival/generalized_rcnn/model_final.pkl \
   videos 

Found Detectron ops lib: /usr/local/lib/python3.7/dist-packages/torch/lib/libcaffe2_detectron_ops_gpu.so
[E init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
INFO io.py: 112: Downloading remote file https://dl.fbaipublicfiles.com/detectron/37698009/12_2017_baselines/e2e_keypoint_rcnn_R-101-FPN_s1x.yaml.08_45_57.YkrJgP6O/output/train/keypoints_coco_2014_train:keypoints_coco_2014_valminusminival/generalized_rcnn/model_final.pkl to /tmp/detectron-download-cache/37698009/12_2017_baselines/e2e_keypoint_rcnn_R-101-FPN_s1x.ya

In [9]:
# fit detectron output to videopose input
!mkdir ./VideoPose3D/data/detectronoutput
!cp output/video.mp4.npz VideoPose3D/data/detectronoutput/video.mp4.npz
os.chdir('VideoPose3D/data') # This script must be launched from the "data" directory
!python prepare_data_2d_custom.py -i detectronoutput -o myvideos
os.chdir('../../')

Parsing 2D detections from detectronoutput
Processing detectronoutput/video.mp4.npz
120 total frames processed
5 frames were interpolated
----------
Saving...
Done.


In [10]:
#Compute 3D Joints with VideoPose3D
!cp ./videos/video.mp4 VideoPose3D/video.mp4
os.chdir('VideoPose3D')
!python run.py -d custom -k myvideos -arc 3,3,3,3,3 -c checkpoint --evaluate pretrained_h36m_detectron_coco.bin --render --viz-subject video.mp4 --viz-action custom --viz-camera 0 --viz-video video.mp4 --viz-output output.mp4 --viz-export outputfile --viz-size 6

Namespace(actions='*', architecture='3,3,3,3,3', batch_size=1024, bone_length_term=True, by_subject=False, causal=False, channels=1024, checkpoint='checkpoint', checkpoint_frequency=10, data_augmentation=True, dataset='custom', dense=False, disable_optimizations=False, downsample=1, dropout=0.25, epochs=60, evaluate='pretrained_h36m_detectron_coco.bin', export_training_curves=False, keypoints='myvideos', learning_rate=0.001, linear_projection=False, lr_decay=0.95, no_eval=False, no_proj=False, render=True, resume='', stride=1, subjects_test='S9,S11', subjects_train='S1,S5,S6,S7,S8', subjects_unlabeled='', subset=1, test_time_augmentation=True, viz_action='custom', viz_bitrate=3000, viz_camera=0, viz_downsample=1, viz_export='outputfile', viz_limit=-1, viz_no_ground_truth=False, viz_output='output.mp4', viz_size=6, viz_skip=0, viz_subject='video.mp4', viz_video='video.mp4', warmup=1)
Loading dataset...
Preparing data...
Loading 2D detections...
INFO: Receptive field: 243 frames
INFO: Tr

In [11]:
#inspect joints export 

import numpy as np
data  = np.load('outputfile.npy')
lst = data
for item in lst:
    print(item)
 


[[-1.01632395e-05 -2.16914596e-05 -1.18287062e-06]
 [-1.20905995e-01 -1.86052788e-02  5.38022369e-02]
 [-9.08533037e-02  4.52056289e-01  1.35828242e-01]
 [-5.33658229e-02  8.97321880e-01  2.53019512e-01]
 [ 1.20906517e-01  1.86025836e-02 -5.37981391e-02]
 [ 1.73069701e-01  4.88167882e-01 -4.15882654e-03]
 [ 2.42984533e-01  9.34685528e-01  9.72532183e-02]
 [ 5.37239984e-02 -2.49864340e-01  1.47789754e-02]
 [ 1.78233087e-02 -4.91871297e-01 -5.89070842e-02]
 [-2.34574415e-02 -5.51845908e-01 -1.42846942e-01]
 [-6.86667440e-03 -6.61833763e-01 -1.19383186e-01]
 [ 1.37220770e-01 -4.25811946e-01 -1.05476886e-01]
 [ 3.01760256e-01 -2.08905786e-01 -2.07411081e-01]
 [ 1.54976070e-01 -2.95303762e-04 -1.75568745e-01]
 [-8.98147970e-02 -4.36416805e-01  2.74297334e-02]
 [-2.61595696e-01 -2.52837062e-01  1.89292580e-01]
 [-2.02303678e-01 -4.33608890e-02  9.02233720e-02]]
[[-1.01821679e-05 -2.17682646e-05 -1.15044281e-06]
 [-1.21052444e-01 -1.85960326e-02  5.36855645e-02]
 [-9.07925144e-02  4.51926470e

In [12]:
#display video
def show_local_mp4_video(file_name, width=640, height=480):
  import io
  import base64
  from IPython.display import HTML
  video_encoded = base64.b64encode(io.open(file_name, 'rb').read())
  return HTML(data='''<video width="{0}" height="{1}" alt="test" controls>
                        <source src="data:video/mp4;base64,{2}" type="video/mp4" />
                      </video>'''.format(width, height, video_encoded.decode('ascii')))

show_local_mp4_video('output.mp4', width=960, height=720)

In [13]:
#Download Joint Export & Video
from google.colab import files


files.download('output.mp4')
files.download('outputfile.npy')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [16]:
import h5py
from utils import smooth, vis, camera
subject = 'S1'
cam_id = '55011271'
cam_params = camera.load_camera_params('/content/cameras.h5')[subject][cam_id]
R = cam_params['R']
T = 0
azimuth = cam_params['azimuth']

pose3d_world = camera.camera2world(pose=data, R=R, T=T)
pose3d_world[:, :, 2] -= np.min(pose3d_world[:, :, 2]) # rebase the height

pose3d_file =  'outputfile.npy'
np.save(pose3d_file, pose3d_world)

In [17]:
from pathlib import Path
from bvh_skeleton import openpose_skeleton, h36m_skeleton, cmu_skeleton

video_file = Path('/content/VideoPose3D/output.mp4') # video file to process
output_dir = Path(f'miscs/{video_file.stem}_cache')
if not output_dir.exists():
    os.makedirs(output_dir)

bvh_file = output_dir / f'{video_file.stem}.bvh'
cmu_skel = cmu_skeleton.CMUSkeleton()
channels, header = cmu_skel.poses2bvh(pose3d_world, output_file=bvh_file)

In [18]:
output = 'miscs/h36m_cxk.bvh'
h36m_skel = h36m_skeleton.H36mSkeleton()
_ = h36m_skel.poses2bvh(pose3d_world, output_file=output)

files.download(output)
files.download(bvh_file)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>