In [1]:
import os
#copy file from helper_video2bvh
!git clone https://github.com/lalasray/helper_video2bvh
#!mv "/content/helper_video2bvh/bvh_skeleton" "/content"
#!mv "/content/helper_video2bvh/utils" "/content"
#!mv "/content/helper_video2bvh/cameras.h5" "/content"

Cloning into 'helper_video2bvh'...
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 18 (delta 2), reused 18 (delta 2), pack-reused 0
Unpacking objects: 100% (18/18), done.


In [2]:
os.chdir('helper_video2bvh')
from google.colab import files
files.upload()
import numpy as np
data  = np.load('outputfile.npy')
lst = data
for item in lst:
    print(item)



Streaming output truncated to the last 5000 lines.
 [-3.1577286e-01 -1.6553354e-01 -1.8416733e-02]
 [-1.8982732e-01 -6.1303817e-02 -1.5232456e-01]]
[[-3.6180718e-06 -8.6882690e-05  2.3218449e-06]
 [-1.5735845e-01  3.2870262e-04  1.5151803e-03]
 [-3.3195180e-01  4.6818244e-01  1.2085409e-01]
 [-3.6079699e-01  8.5110974e-01  3.3042774e-01]
 [ 1.5735742e-01 -3.3749291e-04 -1.4888211e-03]
 [ 3.0007684e-01  4.5923871e-01  8.3416499e-02]
 [ 2.4798341e-01  8.5208774e-01  2.9079658e-01]
 [-1.3017127e-02 -2.5474876e-01 -4.8555031e-02]
 [-2.9981768e-02 -4.8092490e-01 -1.8967062e-01]
 [-3.4583967e-02 -5.7042426e-01 -2.9020822e-01]
 [-4.2175539e-02 -6.7457092e-01 -2.2221380e-01]
 [ 1.2225921e-01 -4.1494724e-01 -1.5773827e-01]
 [ 2.5700271e-01 -1.5893832e-01 -5.4263975e-02]
 [ 1.5333235e-01  3.9826877e-02 -1.2957941e-01]
 [-1.7298380e-01 -4.0550578e-01 -1.3407704e-01]
 [-3.1866613e-01 -1.5489784e-01 -1.8807719e-02]
 [-1.9249782e-01 -6.1724350e-02 -1.4958042e-01]]
[[-2.24332325e-06 -8.96580968e-05  

In [3]:
import h5py
from utils import smooth, vis, camera
subject = 'S1'
cam_id = '55011271'
cam_params = camera.load_camera_params('cameras.h5')[subject][cam_id]
R = cam_params['R']
T = 0
azimuth = cam_params['azimuth']

pose3d_world = camera.camera2world(pose=data, R=R, T=T)
pose3d_world[:, :, 2] -= np.min(pose3d_world[:, :, 2]) # rebase the height

pose3d_file =  'outputfile.npy'
np.save(pose3d_file, pose3d_world)

In [4]:
from pathlib import Path
from bvh_skeleton import openpose_skeleton, h36m_skeleton, cmu_skeleton

#for genrating h36m skeleton
output = 'miscs/h36m_cxk.bvh'
h36m_skel = h36m_skeleton.H36mSkeleton()
_ = h36m_skel.poses2bvh(pose3d_world, output_file=output)
files.download(output)

########################################################################################
#for genrating cmu skeleton/ in-case the other skeleton animations are wrong execute
#video_file = Path('/content/VideoPose3D/output.mp4')
#output_dir = Path(f'miscs/{video_file.stem}_cache')
#if not output_dir.exists():
#    os.makedirs(output_dir)

#bvh_file = output_dir / f'cmu.bvh'
#cmu_skel = cmu_skeleton.CMUSkeleton()
#channels, header = cmu_skel.poses2bvh(pose3d_world, output_file=bvh_file)
#files.download(bvh_file)
########################################################################################



<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>